name: Chili
region: US
source:
  url: https://cookieandkate.com/vegetarian-chili-recipe/
ingredients:
  - item: extra-virgin olive oil
    unit: Tbsp
    amount: 2
  - item: salt
    unit: tsp
    amount: 0.5
  - item: chili powder (non-spicy) - see recipe
    unit: Tbsp
    amount: 6
  - item: bay leaf
    amount: 1
  - item: medium sweet onion, chopped
    amount: 1
  - item: large red bell pepper, chopped
    amount: 1
  - item: medium carrots, chopped
    amount: 2
  - item: celery, chopped
    unit: sticks
    amount: 2
  - item: garlic, pressed or minced
    unit: clove
    amount: 4
  - item: diced tomatoes with juice
    unit: Oz
    amount: 30
  - item: black beans, rinsed and drained
    unit: Oz
    amount: 30, less without can juice
  - item: pinto beans, rinsed and drained
    unit: Oz
    amount: 15, less without can juice
  - item: vegetable broth or water
    unit: cup
    amount: 2
  - item: sherry vinegar or red wine vinegar or lime juice
    unit: tsp
    amount: 1
optional:
  - item: maple syrup
    unit: Tbsp
    amount: 1
  - item: cocoa powder
    unit: Tbsp
    amount: 1
  - item: broccoli, chopped
    unit: Oz
    amount: 16
  - item: meaty tofu crumbles
    unit: Oz
    amount: 16
substitutions:
  - item: chickpeas
    unit: Oz
    amount: 45, less without can juice
    replaces: black and pinto beans
garnishes:
  - item: chopped cilantro
  - item: sliced avocado
  - item: tortilla chips
  - item: grated vegan cheese
  - item: vegan sour cream
steps:
  - Optional: Make meaty tofu crumbles
  - In a large Dutch oven or heavy-bottomed pot over medium heat, warm the olive oil until shimmering. Add the chopped onion, bell pepper, carrot, celery and salt. Stir to combine and cook, stirring occasionally, until the vegetables are tender and the onion is translucent, about 7 to 10 minutes.
  - Add the garlic and chili powder. Cook until fragrant while stirring constantly, about 1 minute.
  - Optional: Add maple syrup and cocoa powder
  - Optional: Add broccoli
  - Add the diced tomatoes and their juices, the drained black beans and pinto beans, vegetable broth and bay leaf. Stir to combine and let the mixture come to a simmer. Continue cooking, stirring occasionally and reducing heat as necessary to maintain a gentle simmer, for 30 minutes.
  - Remove the chili from the heat and discard the bay leaf. For the best texture and flavor, transfer 1.5 cups of the chili to a blender, making sure to get some of the liquid portion. Securely fasten the lid and blend until smooth (watch out for hot steam), then pour the blended mixture back into the pot. (Or, you can blend the chili briefly with an immersion blender, or mash the chili with a potato masher until it reaches a thicker, more chili-like consistency.)
  - Optional: Stir in meaty tofu crumbles
  - Add the chopped cilantro, stir to combine, and then mix in the vinegar, to taste. Divide the mixture into individual bowls and serve with garnishes of your choice. This chili will keep well in the refrigerator for about 4 days or you can freeze it for longer-term storage.
